# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField(choices=[(10, b'Fall'), (20, b'Spring'), (30, b'Summer')])),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
