# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-27 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
