# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-21 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='meetings',
        ),
        migrations.AddField(
            model_name='coursemeeting',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
