# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20161022_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
