# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20161022_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
