# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-24 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20161022_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
    ]
