# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20161024_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.TextField(default=b''),
        ),
    ]
