#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
cp -r $OPENSHIFT_REPO_DIR/data/* $OPENSHIFT_DATA_DIR

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

python $OPENSHIFT_REPO_DIR/wsgi/rice_course_manager/manage.py makemigrations --noinput
python $OPENSHIFT_REPO_DIR/wsgi/rice_course_manager/manage.py syncdb --noinput
python $OPENSHIFT_REPO_DIR/wsgi/rice_course_manager/manage.py collectstatic --noinput