# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0009_auto_20150413_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='shown',
            new_name='active',
        ),
    ]
