# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-05 18:38
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations
import me.util


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0011_auto_20160515_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=colorful.fields.RGBColorField(default=me.util.random_hex_color),
        ),
    ]
