# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-21 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20161021_1730'),
        ('me', '0012_schedule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='term',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Term'),
            preserve_default=False,
        ),
    ]
