# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0009_auto_20151102_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='tutorial',
        ),
        migrations.AlterModelOptions(
            name='helparticle',
            options={},
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='order',
        ),
        migrations.AddField(
            model_name='helparticle',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
